name: golangci-lint
on:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install libpcap-dev
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Read .go-version file
        id: goversion
        run: echo "::set-output name=version::$(cat .go-version)"

      - uses: actions/setup-go@v5
        with:
          go-version: "${{ steps.goversion.outputs.version }}"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v1.61
          args: --timeout=5m

          # Ignore pre-existing issues.
          only-new-issues: true
